from importlib.metadata import EntryPoint
from re import L
from tkinter import *
from tkinter import messagebox
root =Tk()
regp=Label(root,text='Registration Period : ').grid(row=1,column=)
regt=Label(root,text='Registration Type : ').grid(row=1,column=)
v=IntVar()
regp1 =Radiobutton(root,text = "One Year", variable = v, value =1).grid(row=1,column=)
regp2 =Radiobutton(root,text = "Two Year", variable = v, value =2).grid(row=1,column=)
regp3 =Radiobutton(root,text = "Three Year", variable = v, value =3).grid(row=1,column=)

regt1 =Radiobutton(root,text = "One Year", variable = v, value =1).grid(row=1,column=)
regt2 =Radiobutton(root,text = "Two Year", variable = v, value =2).grid(row=1,column=)
regt3 =Radiobutton(root,text = "Three Year", variable = v, value =3).grid(row=1,column=)
regt4 =Radiobutton(root,text = "One Year", variable = v, value =1).grid(row=1,column=)
regt5 =Radiobutton(root,text = "Two Year", variable = v, value =2).grid(row=1,column=)
regt6 =Radiobutton(root,text = "Three Year", variable = v, value =3).grid(row=1,column=)
regt7 =Radiobutton(root,text = "One Year", variable = v, value =1).grid(row=1,column=)
regt8 =Radiobutton(root,text = "Two Year", variable = v, value =2).grid(row=1,column=)
regt9 =Radiobutton(root,text = "Three Year", variable = v, value =3).grid(row=1,column=)
regt10 =Radiobutton(root,text = "One Year", variable = v, value =1).grid(row=1,column=)
regt11 =Entry(root,text = "Two Year").grid(row=1,column=)
own=Label(root,text="Owners Full Name : ").grid(row=, column=)
telno=Label(root,text='Registration Period : ').grid(row=1,column=)
dmv=Label(root,text='Registration Period : ').grid(row=1,column=)
cown=Label(root,text="Owners Full Name : ").grid(row=, column=)
ctelno=Label(root,text='Registration Period : ').grid(row=1,column=)
cdmv=Label(root,text='Registration Period : ').grid(row=1,column=)
note=Label(root,text="Owners(and lesses if applicable)MUST provide their residence/home/business address where requested, this address \n cannot be a P.O. Box. You Must complete form ISD-01 if you would like your address(es) updated.").grid(row=,column=)
rbj=Label(root,text="Residence/Business Juridiction: ").grid(row=,column=)
rbje=Entry(root,)
ownadd=Label(root,text="Owner's Resisdence/Home/Business Address (Apt # if applicable)").grid(row=,column=)
ocity=Label(root,text="City").grid(row=,column=)
ostate=Label(root,text="State").grid(row=,column=)
oZipcode=Label(root,text="ZIP CODE: ").grid(row=,column=)
cownadd=Label(root,text="CO-Owner's Resisdence/Home/Business Address (Apt # if applicable)").grid(row=,column=)
cocity=Label(root,text="City").grid(row=,column=)
costate=Label(root,text="State").grid(row=,column=)
coZipcode=Label(root,text="ZIP CODE: ").grid(row=,column=)
oemail=Label(root,text="Owner Email Address: ").grid(row=, column = )
coemail=Label(root,text="Co-Owner Email Address: ").grid(row=, column = )

loc=Label(root,text="Location where vehicle is principally garaged : ", variable = v, value =1)
cityc=Radiobutton(root,text="City " ,variable = v, value =1).grid(row=, column = )
countryc=Radiobutton(root,text="Country", variable = v, value =1).grid(row=, column = )
townc=Label(root,text="Town of ").grid(row=,column=)
townce=Entry(root)

#CreditCard.grid(row=40, column = 7)
CreditCard =Radiobutton(root,text = "Direct Bank Transfer", variable = v, value =2)
def smit():
        messagebox.showinfo("Submitted", "Your Data has been submitted!!")
submit = Button(root, text = 'Submit', bd = '5', command = smit).grid(row=42,column=7)

mainloop()